name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          # Cloudflare Pages uses Node.js 22.16
          node-version: 22.16
          cache: 'npm'
      - run: npm i
      - run: npm run build